name: Unpack Archive

on:
  push:
    branches:
      - main

jobs:
  unpack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Unpack archive
        run: unzip api.zip
